name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Python dependencies
      run: pip3 install numpy python-dateutil pytz pytest

    - name: Build
      run: make -j 3

    - name: Run tests
      run: make -k test

    - name: Run time zone tests
      run: pytest -m fulltz

